# Dependencies

highlighter:      rouge

# Permalinks
permalink:        pretty


# Setup
title:            Eerie Island
tagline:          'A Local Multiplayer Game Company'
description:      'https://github.com/poole/hyde.git'
url:              http://www.eerieisland.com
baseurl:          http://www.eerieisland.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
